#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();
$application->setName('FreeAPI');

# add our commands
$application->add(new Server());
$application->add(new Model());
$application->add(new Controller());

$application->run();